name: test

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v1
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm test